### ISSUE TITLE
Differences between plugin installation instructions

### ISSUE THREAD

**Issue by KimAndGumi** [Findus23/plugin-SentryLogger#14]
I would like to use the Sentry plugin but I'm confused in the installation process. 
From the [README.md](https://github.com/digitalist-se/MatomoPlugin-Sentry/tree/5.x-dev?tab=readme-ov-file#installation) I understand I must run `composer install --no-dev` from root of Matomo project.
But in the [documentation on plugins.matomo.org](https://plugins.matomo.org/Sentry#documentation), `composer install --no-dev` must be run from inside plugins/Sentry folder.
Which instructions are the right one ?

**Comment by mikkeschiren** [comment]
Sorry for the confusion - `composer install --no-dev` - should be runned in the plugin folder. I will make sure to update the documentation.

**Comment by mikkeschiren** [comment]
This should now be fixed.
