### ISSUE TITLE
The plugin '' has not been loaded. at /index.php

### ISSUE THREAD

**Issue by mfb** [Findus23/plugin-SentryLogger#3]
When the Sentry plugin is enabled, I get

An error occurred
The plugin '' has not been loaded.

when attempting to load /index.php

**Comment by Findus23** [comment]
Hi,

Interestingly I had the same bug. But every time I tried to debug it and disabled and reenabled it, the error was suddenly gone. 
I think it has something to do with an error in this function (https://github.com/Findus23/plugin-SentryLogger/blob/master/SentryLogger.php#L22) or maybe just an old cache. 

Lukas

**Comment by mfb** [comment]
For me, the error happens if the Sentry PHP DSN is configured.  If I set it to empty string then everything works.

It also causes some 500 errors when websites load the tracker - I have 1000 events in sentry related to this.. so at least that part is working :p    But unfortunately I'll need to disable the plugin if there are some 500 errors.

**Comment by Findus23** [comment]
This makes sense as the plugin does nothing if the dsn is an empty string. 

Maybe one of these throw an error
https://github.com/Findus23/plugin-SentryLogger/blob/master/SentryLogger.php#L37-L43
And therefore stop Matomo from loading plugins and therefore working at all. 

Lukas

**Comment by mfb** [comment]
Well, you can see the stacktrace in Sentry -

the problematic line is  `"currentPlugin" => Piwik::getCurrentPlugin()->pluginName,`

**Comment by Findus23** [comment]
Now that I think about it, fetching the list of all plugins during initialising of plugins doesn't seem that smart :)

I have removed that line in 0.2.3

**Comment by mfb** [comment]
Seems resolved.
